// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe4EDibcO-aQXNIP6yZ3RC-vae8WVQNbI',
    appId: '1:263866298324:web:f46e06125b7066ac43b041',
    messagingSenderId: '263866298324',
    projectId: 'evently-app-63241',
    authDomain: 'evently-app-63241.firebaseapp.com',
    storageBucket: 'evently-app-63241.firebasestorage.app',
    measurementId: 'G-9TCV9ZH8RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLkm_TjSp4t3xOWRFDRaQAWwXpVEebaw',
    appId: '1:263866298324:android:e0f1d9b46ad036eb43b041',
    messagingSenderId: '263866298324',
    projectId: 'evently-app-63241',
    storageBucket: 'evently-app-63241.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmf3zAVTT4IPccIPrtUWnfJZfhcMs7rSY',
    appId: '1:263866298324:ios:b58f4eef80e21f0f43b041',
    messagingSenderId: '263866298324',
    projectId: 'evently-app-63241',
    storageBucket: 'evently-app-63241.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmf3zAVTT4IPccIPrtUWnfJZfhcMs7rSY',
    appId: '1:263866298324:ios:b58f4eef80e21f0f43b041',
    messagingSenderId: '263866298324',
    projectId: 'evently-app-63241',
    storageBucket: 'evently-app-63241.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe4EDibcO-aQXNIP6yZ3RC-vae8WVQNbI',
    appId: '1:263866298324:web:0f3c9d842206a62a43b041',
    messagingSenderId: '263866298324',
    projectId: 'evently-app-63241',
    authDomain: 'evently-app-63241.firebaseapp.com',
    storageBucket: 'evently-app-63241.firebasestorage.app',
    measurementId: 'G-EDQFYSYZZG',
  );
}
